guide/urls.py
from django.urls import path,include
from django.conf.urls import url
from . import views

app_name="guide"

urlpatterns = [
    url(r'^$', views.NumaraListele.as_view(), name='numara_liste'),
    url(r'^(?P<pk>\d+)$', views.numara_detay, name='numara_detay'),
    url(r'^(?P<pk>[0-9]+)/guncelle/$', views.NumaraGuncelle.as_view(), name='numara_guncelle'),
    url(r'^sil/(?P<pk>[0-9]+)/$', views.NumaraSil.as_view(), name='numara_sil'),
    url(r'^olustur/$', views.NumaraOlutur.as_view(), name='numara_olustur'),
]

rehber/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('guide.urls')),
]

guide/models.py
from django.db import models

# Create your models here.
class Guide(models.Model):
    isim = models.CharField(verbose_name="İsim", max_length=20)
    soyisim = models.CharField(verbose_name="Soyisim", max_length=20)
    numara = models.IntegerField(default=0, unique=True)

    def __str__(self):
        return self.get_full_name()

    def get_full_name(self):
        return '{isim} {soyisim}'.format(
            isim=self.isim,
            soyisim=self.soyisim
        )

guide/forms.py
from django import forms
from .models import Guide
from django.db import models


class GuideForm(forms.ModelForm):
    class Meta:
        model = Guide
        fields = ('isim', 'soyisim', 'numara')

guide/views.py
from django.shortcuts import render,get_object_or_404
from django.views import generic
from django.views.generic import UpdateView, DeleteView, CreateView

from .models import Guide
from .forms import GuideForm


# Create your views here.

class NumaraListele(generic.ListView):
    model = Guide
    template_name = 'kisi_liste.html'
    success_url = '/'
    
    def get_queryset(self):
        return Guide.objects.all()

class NumaraOlutur(CreateView):
    model = Guide
    form_class = GuideForm
    template_name = 'kisi_duzenle.html'
    success_url = '/'

    def form_valid(self, form):
        self.objects = form.save(commit=False)
        self.objects.user = self.request.user
        self.objects.save()
        return super().form_valid(form)

class NumaraGuncelle(UpdateView):
    model = Guide
    form_class = GuideForm
    template_name = 'kisi_duzenle.html'
    success_url = '/'

    def get_object(self):
        return Guide.objects.get(pk=self.kwargs['pk'])

    def form_valid(self, form):
        self.objects = form.save(commit=False)
        self.objects.user = self.request.user
        self.objects.save()
        return super().form_valid(form)

class NumaraSil(DeleteView):
    model = Guide
    success_url = '/'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

def numara_detay(request, pk):
    numaralar = get_object_or_404(Guide, pk=pk)
    return render(request, 'kisi_detay.html', {'numaralar': numaralar})

templates/base.html
{% load static %}

<html lang="tr">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/guide.css' %}">
    <title>Rehber</title>
</head>
<body>
    <div style = "margin-top : 50px; margin-bottom:50px;" class = "container">
        <div class="jumbotron text-center">
            <h1><a href="/">Telefon Rehberi</a></h1>
        </div>
        <div style = "margin-top : 10px; margin-bottom:10px;" class = "container text-center">
            <a href="{% url 'guide:numara_olustur' %}"><button type="button" class="btn btn-primary glyphicon glyphicon-plus">Kişi Ekle</button></a>
        </div>

        <div class="jumbotron text-left">
        {% block content %}
        
        {% endblock %}
        </div>
    </div>
</body>
</html>

templates/kisi_detay.html
{% extends 'base.html' %}

{% block content %}
<div class = "row justify-content-between">
  <h1>{{ numaralar.isim }}  {{ numaralar.soyisim }}</h1>
  <p>{{ numaralar.numara }}</p>
  <a class="btn btn-warning" href="{% url 'guide:numara_guncelle' pk=numaralar.pk %}">
    <span class="glyphicon glyphicon-pencil"></span>
  </a>
  <a class="btn btn-danger" href="{% url 'guide:numara_sil' pk=numaralar.pk %}">
    <span class="glyphicon glyphicon-trash"></span>
  </a>
</div>
{% endblock %}

templates/kisi_duzenle.html
{% extends 'base.html' %}

{% block content %}
    <h1>Yeni Kişi</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Kaydet</button>
    </form>
{% endblock %}

templates/kisi_liste.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-between">
    {% for guide in object_list %}
    <div class = "list-group-item list-group-item-action align-items-center d-flex">
      <h1><a href="{% url 'guide:numara_detay' pk=guide.pk %}">
        {{ guide.isim }}  {{ guide.soyisim }}</a>
      </h1>
        <p>{{ guide.numara }}</p>
    </div>
    {% endfor %}
</div>   
{% endblock %}